<center style="font-size: 26px"> <b>Проверка уровня знаний Python</b></center>

In [ ]:
# обеспечиваем совместимость с Python 2 и 3
from __future__ import (absolute_import, division, print_function, unicode_literals)

# отключаем предупреждения дистрибутива Anaconda
import warnings
warnings.simplefilter('ignore')

**Описание датасета:**   
[Датасет вакансий с платформы HH.ru на Kaggle.com](https://www.kaggle.com/datasets/pavfedotov/heaadhunter-vacancies?resource=download&select=df2021-08-03.csv) 

Нужный файл - df2021-08-03.csv.

- *vacancy* - наименование вакансии
- *url* - ссылка на вакансию
- *created* - дата и время создания
- *has_test* - наличие тестового задания в вакансии
- *salary_from* - нижняя граница значения заработной платы
- *salary_to* - верхняя граница значения заработной платы
- *currency* - валюта заработной платы
- *experience* - требуемый опыт
- *schedule* - тип рабочего графика
- *skills* - требуемые навыки
- *employer* - наименование работодателя
- *area* - наименование города
- *description* - описание вакансии

#### Загрузите датасет

In [2]:
# импорт необходимой библиотеки
import pandas as pd

# загрузка таблицы из .csv
df = pd.read_csv(r"D:\Users\Andrew\Desktop\Поиск работы\Отклики\Биокад\Стажировка\DE\Тестовое задание\df2021-08-03.csv")

# изучим данные
df.info()
df.describe()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1700 entries, 0 to 1699
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vacancy      1700 non-null   object
 1   url          1700 non-null   object
 2   created      1700 non-null   object
 3   has_test     1700 non-null   bool
 4   salary_from  538 non-null    float64
 5   salary_to    433 non-null    float64
 6   currency     613 non-null    object
 7   experience   1700 non-null   object
 8   schedule     1700 non-null   object
 9   skills       1490 non-null   object
 10  employer     1700 non-null   object
 11  area         1700 non-null   object
 12  description  1700 non-null   object
dtypes: bool(1), float64(2), object(10)
memory usage: 161.2+ KB

,vacancy,url,created,has_test,salary_from,salary_to,currency,experience,schedule,skills,employer,area,description
0,Backend/Full-stack developer (python),https://hh.ru/applicant/vacancy_response?vacan...,2021-08-01T13:02:48+0300,False,120000.0,NaN,RUR,От 1 года до 3 лет,Гибкий график,Python;PostgreSQL;Linux;Flask;,ATI.SU,Санкт-Петербург,Привет! Мы ATI.SU ― крупнейшая в России компан...
1,Бэкенд-разработчик (Python) / Middle Python / ...,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-09T08:13:01+0300,False,150000.0,220000.0,RUR,От 3 до 6 лет,Удаленная работа,Python;Git;MongoDB;Redis;Design Patterns;Flask;,"ЮТэйр, Авиакомпания",Киров (Кировская область),Utair - российская авиакомпания. Мы летаем по ...
2,Fullstack Middle Python (Django) / VueJS Dev,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-21T15:24:16+0300,False,NaN,NaN,NaN,От 1 года до 3 лет,Полный день,Python;Git;Django Framework;PostgreSQL;Linux;V...,КРОК,Москва,"В команду, которая занимается разработкой инст..."
3,Python Developer,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-28T12:57:57+0300,False,NaN,NaN,NaN,От 3 до 6 лет,Удаленная работа,Python;Django Framework;CSS;,Mad Devs,Краснодар,Mad Devs - full stack команда для разработки и...
4,QA Automation (Python),https://hh.ru/applicant/vacancy_response?vacan...,2021-07-31T17:10:49+0300,False,NaN,NaN,NaN,От 1 года до 3 лет,Удаленная работа,Python;Pytest;Ansible;Selenium;,Аренадата Софтвер,Москва,"Arenadata — динамично развивающаяся компания, ..."
5,Data Engineer / Python Developer,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-28T14:58:53+0300,False,NaN,NaN,NaN,От 1 года до 3 лет,Полный день,NaN,Devim,Санкт-Петербург,Привет! На связи Devim. Для начала – немного о...
6,Python developer,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-12T12:18:41+0300,False,NaN,NaN,NaN,Нет опыта,Полный день,Python;Django Framework;PostgreSQL;Linux;,Factory5,Казань,О компании. Factory5 (группа Ctrl2GO) — разраб...
7,Ведущий Python разработчик,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-06T23:46:27+0300,False,200000.0,350000.0,RUR,Более 6 лет,Полный день,Python;Node.js;HTTP;Git;TCP/IP;JavaScript;PHP;...,ODDSCORP,Москва,"Мы - команда проекта ODDSCORP, небольшая групп..."
8,Разработчик Python,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-27T09:59:22+0300,False,90000.0,180000.0,RUR,От 1 года до 3 лет,Гибкий график,Python;MySQL;Базы данных;SQL;Linux;Django Fram...,The Head,Екатеринбург,19 лет The Head создает и развивает IT-инфраст...
9,Python developer with AWS expertise,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-13T11:06:01+0300,False,NaN,NaN,NaN,Более 6 лет,Гибкий график,Python;Cloud technologies;AWS;SaaS;Git;Jenkins...,Deutsche Telekom IT Solutions (ex.T-Systems),Санкт-Петербург,Telekom IT is an integral part of Deutsche Tel...

### Практические задания:

#### 1. Изучите методы для сбора данных курсов валют в [API Центрального банка Российской Федерации](https://www.cbr.ru/development/SXML/) . Используя запросы к API, приведите значения заработной платы к рублям одним из вариантов: 1) простой вариант - на текущую дату  2) вариант посложнее - на дату создания (created).

In [3]:
# преобразуем формат в дату
import datetime as dt
df['created'] = pd.to_datetime(df['created'])
df["date"] = pd.to_datetime(df['created'].dt.date)

# находим минимальные и максимальные даты для выгрузки курсов валют
min_date = df["date"].min()
max_date = df["date"].max()

# Преобразование дат в формат DD/MM/YYYY
min_date_formatted = min_date.strftime('%d/%m/%Y')
max_date_formatted = max_date.strftime('%d/%m/%Y')

In [4]:
# Определим уникальные валюты используемые в выборке вакансий
df["currency"].unique()

array(['RUR', nan, 'EUR', 'USD'], dtype=object)

Обнаружили, что заработную плату указывают в рублях, евро и долларах. Также есть пустые значения, которые считаем рублями.

In [5]:
# Создадим словарь кодов необходимых для перевода в рубли валют
currency_dict = {
    "EUR": "R01239",
    "USD": "R01235"
}

In [6]:
# Импортируем необходимые для получения и парсинга API ответа библиотеки
import requests
import xml.etree.ElementTree as ET

# Считываем и собираем в таблицу данные
data = []

for key, value in currency_dict.items():
    url = f"https://www.cbr.ru/scripts/XML_dynamic.asp?date_req1={min_date_formatted}&date_req2={max_date_formatted}&VAL_NM_RQ={value}"
    response = requests.get(url)

    if response.status_code == 200:
        root = ET.fromstring(response.content)

        for record in root.findall('.//Record'):
            date = record.get('Date')
            value = record.find('Value').text

            data.append({
                'Currency_name': key,
                'Date': pd.to_datetime(date),
                'Value': value.replace(',', '.')
            })
    else:
        print(f"Ошибка при выполнении запроса: {response.status_code}")

# Создание DataFrame из собранных данных
df_currencies = pd.DataFrame(data)
df_currencies["Value"] = df_currencies['Value'].astype(float)
df_currencies.info()

C:\Users\Андрей\AppData\Local\Temp\ipykernel_18120\189807867.py:21: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  'Date': pd.to_datetime(date),

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Currency_name  42 non-null     object
 1   Date           42 non-null     datetime64[ns]
 2   Value          42 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 1.1+ KB

In [7]:
# добавляем необходимые значения курса соответствующих валют в соответствующий день размещения вакансии
merged_df = pd.merge(df,
                     df_currencies, 
                     how = "left", 
                     left_on = ["date", "currency"], 
                     right_on = ["Date", "Currency_name"])
merged_df = merged_df.drop(columns = ["Currency_name", "Date"])

# заполняем пропуски в столбцах
merged_df["Value"] = merged_df["Value"].fillna(1)
merged_df["salary_to"] = merged_df["salary_to"].fillna(merged_df["salary_from"])
merged_df["salary_from"] = merged_df["salary_from"].fillna(merged_df["salary_to"])
merged_df["rur_salary_from"] = merged_df['salary_from']*merged_df["Value"]
merged_df["rur_salary_to"] = merged_df['salary_to']*merged_df["Value"]

# рассчитываем среднее значение зарплаты для каждой вакансии, потребуется в следующих заданиях
merged_df['rur_avg_salary'] = merged_df[['rur_salary_from', 'rur_salary_to']].mean(axis = 1)

# выводим результат
merged_df.head(10)

,vacancy,url,created,has_test,salary_from,salary_to,currency,experience,schedule,skills,employer,area,description,date,Value,rur_salary_from,rur_salary_to,rur_avg_salary
0,Backend/Full-stack developer (python),https://hh.ru/applicant/vacancy_response?vacan...,2021-08-01 13:02:48+03:00,False,120000.0,120000.0,RUR,От 1 года до 3 лет,Гибкий график,Python;PostgreSQL;Linux;Flask;,ATI.SU,Санкт-Петербург,Привет! Мы ATI.SU ― крупнейшая в России компан...,2021-08-01,1.0,120000.0,120000.0,120000.0
1,Бэкенд-разработчик (Python) / Middle Python / ...,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-09 08:13:01+03:00,False,150000.0,220000.0,RUR,От 3 до 6 лет,Удаленная работа,Python;Git;MongoDB;Redis;Design Patterns;Flask;,"ЮТэйр, Авиакомпания",Киров (Кировская область),Utair - российская авиакомпания. Мы летаем по ...,2021-07-09,1.0,150000.0,220000.0,185000.0
2,Fullstack Middle Python (Django) / VueJS Dev,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-21 15:24:16+03:00,False,NaN,NaN,NaN,От 1 года до 3 лет,Полный день,Python;Git;Django Framework;PostgreSQL;Linux;V...,КРОК,Москва,"В команду, которая занимается разработкой инст...",2021-07-21,1.0,NaN,NaN,NaN
3,Python Developer,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-28 12:57:57+03:00,False,NaN,NaN,NaN,От 3 до 6 лет,Удаленная работа,Python;Django Framework;CSS;,Mad Devs,Краснодар,Mad Devs - full stack команда для разработки и...,2021-07-28,1.0,NaN,NaN,NaN
4,QA Automation (Python),https://hh.ru/applicant/vacancy_response?vacan...,2021-07-31 17:10:49+03:00,False,NaN,NaN,NaN,От 1 года до 3 лет,Удаленная работа,Python;Pytest;Ansible;Selenium;,Аренадата Софтвер,Москва,"Arenadata — динамично развивающаяся компания, ...",2021-07-31,1.0,NaN,NaN,NaN
5,Data Engineer / Python Developer,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-28 14:58:53+03:00,False,NaN,NaN,NaN,От 1 года до 3 лет,Полный день,NaN,Devim,Санкт-Петербург,Привет! На связи Devim. Для начала – немного о...,2021-07-28,1.0,NaN,NaN,NaN
6,Python developer,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-12 12:18:41+03:00,False,NaN,NaN,NaN,Нет опыта,Полный день,Python;Django Framework;PostgreSQL;Linux;,Factory5,Казань,О компании. Factory5 (группа Ctrl2GO) — разраб...,2021-07-12,1.0,NaN,NaN,NaN
7,Ведущий Python разработчик,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-06 23:46:27+03:00,False,200000.0,350000.0,RUR,Более 6 лет,Полный день,Python;Node.js;HTTP;Git;TCP/IP;JavaScript;PHP;...,ODDSCORP,Москва,"Мы - команда проекта ODDSCORP, небольшая групп...",2021-07-06,1.0,200000.0,350000.0,275000.0
8,Разработчик Python,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-27 09:59:22+03:00,False,90000.0,180000.0,RUR,От 1 года до 3 лет,Гибкий график,Python;MySQL;Базы данных;SQL;Linux;Django Fram...,The Head,Екатеринбург,19 лет The Head создает и развивает IT-инфраст...,2021-07-27,1.0,90000.0,180000.0,135000.0
9,Python developer with AWS expertise,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-13 11:06:01+03:00,False,NaN,NaN,NaN,Более 6 лет,Гибкий график,Python;Cloud technologies;AWS;SaaS;Git;Jenkins...,Deutsche Telekom IT Solutions (ex.T-Systems),Санкт-Петербург,Telekom IT is an integral part of Deutsche Tel...,2021-07-13,1.0,NaN,NaN,NaN

#### 2. Найдите вакансию с самой высокой заработной платой, где подойдет 4 года опыта работы и не нужно проходить тестовое задание.

In [8]:
# Выводим уникальные значения из столбца опыта работы
merged_df['experience'].unique()

array(['От 1 года до 3 лет', 'От 3 до 6 лет', 'Нет опыта', 'Более 6 лет'],
      dtype=object)

Для получения выборки с вакансиями, где подойдет опыт работы 4 года сделаем фильтрацию по "От 3 до 6 лет" и "Более 6 лет".

In [9]:
# Фильтрация таблицы по требуемым параметрам (опыт работы 4 года и отсутствие тестового задания)
filtered_df = merged_df.query('has_test == False and (experience == "От 3 до 6 лет" or experience == "Более 6 лет")')

# Определим максимальное значение заработной платы в выборке
max_salary = filtered_df['rur_salary_to'].max()

# Фильтрация выборки по максимальному значению заработной платы
filtered_df = filtered_df.query('rur_salary_to == @max_salary')

# вывод результата
filtered_df

,vacancy,url,created,has_test,salary_from,salary_to,currency,experience,schedule,skills,employer,area,description,date,Value,rur_salary_from,rur_salary_to,rur_avg_salary
28,Python backend developer,https://hh.ru/applicant/vacancy_response?vacan...,2021-08-02 09:27:23+03:00,False,150000.0,500000.0,RUR,Более 6 лет,Удаленная работа,Python;MongoDB;PostgreSQL;Docker;Креативность;,HR CITY MOSCOW,Москва,Мы создаем уникальное всемирное мобильное прил...,2021-08-02,1.0,150000.0,500000.0,325000.0
140,"Full-stack Разработчик React, Python",https://hh.ru/applicant/vacancy_response?vacan...,2021-08-01 03:53:23+03:00,False,200000.0,500000.0,RUR,От 3 до 6 лет,Удаленная работа,React;Python;,MINT NFT,Владивосток,"MINT NFT, Inc. - компания занимается разработк...",2021-08-01,1.0,200000.0,500000.0,350000.0
231,Python разработчик (middle) (backend),https://hh.ru/applicant/vacancy_response?vacan...,2021-08-03 11:07:34+03:00,False,500000.0,500000.0,RUR,От 3 до 6 лет,Полный день,Python;Django Framework;PostgreSQL;Linux;SQL;g...,Лендсбэй,Москва,Ищем активного человека с опытом написания раз...,2021-08-03,1.0,500000.0,500000.0,500000.0
1357,"Full-stack Разработчик React, Python",https://hh.ru/applicant/vacancy_response?vacan...,2021-07-23 03:57:53+03:00,False,200000.0,500000.0,RUR,От 3 до 6 лет,Удаленная работа,React;Python;,MINT NFT,Якутск,"MINT NFT, Inc. - компания занимается разработк...",2021-07-23,1.0,200000.0,500000.0,350000.0
1369,"Mobile-Разработчик Flutter, Python",https://hh.ru/applicant/vacancy_response?vacan...,2021-07-22 17:22:35+03:00,False,200000.0,500000.0,RUR,От 3 до 6 лет,Удаленная работа,Flutter;Python;Android;iOS;,MINT NFT,Красноярск,"MINT NFT, Inc. - компания занимается разработк...",2021-07-22,1.0,200000.0,500000.0,350000.0
1373,"Full-stack Разработчик React, Python",https://hh.ru/applicant/vacancy_response?vacan...,2021-07-22 17:14:01+03:00,False,200000.0,500000.0,RUR,От 3 до 6 лет,Удаленная работа,Python;React;,MINT NFT,Санкт-Петербург,"MINT NFT, Inc. - компания занимается разработк...",2021-07-22,1.0,200000.0,500000.0,350000.0
1493,Fullstack Python developer,https://hh.ru/applicant/vacancy_response?vacan...,2021-07-20 12:00:09+03:00,False,200000.0,500000.0,RUR,Более 6 лет,Удаленная работа,Python;Git;SQL;NoSQL;JavaScript;,ODDSCORP,Москва,"Мы - команда проекта ODDSCORP, небольшая групп...",2021-07-20,1.0,200000.0,500000.0,350000.0

#### 3. Сделайте рейтинг (топ-30) навыков по всем вакансиям.

In [10]:
# Импорт счетчика
from collections import Counter

# собираем все скилы в список
all_skills = df['skills'].str.split(';').explode().str.strip().to_list()

# удаляем пустые значения
all_skills = [skill for skill in all_skills if skill]

# считаем количество повторений
skill_counts = Counter(all_skills)

# содздаем датафрейм и сортируем его по количеству
skill_counts_df = pd.DataFrame(skill_counts.items(), columns=['Skill', 'Count'])
skill_counts_df = skill_counts_df.sort_values(by='Count', ascending=False)

# выводим результат
skill_counts_df.head(30)

                Skill  Count
0              Python   1442
4                 Git    586
24                SQL    501
1          PostgreSQL    499
8    Django Framework    467
2               Linux    463
14                NaN    210
3               Flask    177
29             Docker    172
18         JavaScript    149
31    Английский язык    141
22              MySQL    128
41                ООП    120
5             MongoDB    113
6               Redis    107
80               REST     70
53           RabbitMQ     68
57             Django     62
10                CSS     56
47               HTML     56
39     Atlassian Jira     52
20                C++     50
93                API     49
62             MS SQL     43
127              Java     43
23        Базы данных     41
59   Работа в команде     39
26                AWS     36
11             Pytest     35
42             Celery     35

#### 4. Cоставьте топ-10 городов с наибольшей средней заработной платой по вакансиям тестировщика (QA).

In [11]:
# фильтруем вакансии тестировщиков
qa_df = merged_df[merged_df['vacancy'].str.contains('QA', case=False)]

# считаем среднее значение заработной платы тестировщика по городам, сортируем по убыванию и выводим топ-10
avg_salary_top_rate = qa_df.pivot_table(values = 'rur_avg_salary', aggfunc= 'mean', index = 'area').sort_values('rur_avg_salary', ascending= False).head(10)

# выводим результат
avg_salary_top_rate

                 rur_avg_salary
area
Тамбов            200000.000000
Москва            190555.555556
Санкт-Петербург   180555.555556
Казань             90000.000000

#### 5. Напишите функцию для поиска вакансий по переданным в нее значениям заработной платы, наличия тестового задания, наличия заданного текста в наименовании вакансии, наличия заданного навыка. В результате выведите количество найденных вакансий, среднюю заработную плату по найденным вакансиям и список ссылок найденных вакансий.

In [12]:
# функция для поиска вакансий

def vacancy_finder(salary, test_task, vacancy_part, skill):
    # Фильтрация по условиям зарплаты и наличия тестового задания
    df = merged_df.query('''has_test == @test_task and rur_salary_from <= @salary and rur_salary_to >= @salary''')

    # Фильтрация по подстроке в названии вакансии
    df = df[df['vacancy'].str.contains(vacancy_part, case=False, na=False)]

    # Фильтрация по подстроке в навыках
    df = df[df['skills'].str.contains(skill, case=False, na=False)]
    
    # количество вакансий
    vacancies_count = len(df)

    # среднее значение заработной платы по найденным вакансиям
    avg_salary = df['rur_avg_salary'].mean().round(2)

    # список ссылок на вакансии
    url_list = df['url'].to_list()

    return vacancies_count, avg_salary, url_list

# проверка функции
result = vacancy_finder(salary=400000, test_task=False, vacancy_part='Python', skill='Python')

print(result)

(16, np.float64(340668.38), ['https://hh.ru/applicant/vacancy_response?vacancyId=46386511', 'https://hh.ru/applicant/vacancy_response?vacancyId=46604456', 'https://hh.ru/applicant/vacancy_response?vacancyId=46458400', 'https://hh.ru/applicant/vacancy_response?vacancyId=46497746', 'https://hh.ru/applicant/vacancy_response?vacancyId=46718244', 'https://hh.ru/applicant/vacancy_response?vacancyId=46718177', 'https://hh.ru/applicant/vacancy_response?vacancyId=46499976', 'https://hh.ru/applicant/vacancy_response?vacancyId=44433173', 'https://hh.ru/applicant/vacancy_response?vacancyId=46705713', 'https://hh.ru/applicant/vacancy_response?vacancyId=46559189', 'https://hh.ru/applicant/vacancy_response?vacancyId=46417735', 'https://hh.ru/applicant/vacancy_response?vacancyId=46462771', 'https://hh.ru/applicant/vacancy_response?vacancyId=46458369', 'https://hh.ru/applicant/vacancy_response?vacancyId=46458120', 'https://hh.ru/applicant/vacancy_response?vacancyId=46373028', 'https://hh.ru/applicant/vacancy_response?vacancyId=46510274'])

#### *Необязательно*. Усложненный вариант - сделать атрибуты функции опциональными, чтобы иметь возможность фильтрации вакансий по любой комбинации условий.

In [ ]:
# функция с фильтрацией по любой комбинации условий
def vacancy_finder(salary = None, test_task = None, vacancy_part = None, skill = None):
    # создаем копию исходного датафрейма
    df = merged_df.copy()
    
    # Фильтрация по условиям зарплаты 
    if salary is not None:
        df = df.query('''rur_salary_from <= @salary and rur_salary_to >= @salary''')

    # Фильтрация по наличию тестового задания
    if test_task is not None:
        df = df.query('''has_test == @test_task''')

    # Фильтрация по подстроке в названии вакансии
    if vacancy_part is not None:
        df = df[df['vacancy'].str.contains(vacancy_part, case=False, na=False)]

    # Фильтрация по подстроке в навыках
    if skill is not None:
        df = df[df['skills'].str.contains(skill, case=False, na=False)]
    
    # количество вакансий
    vacancies_count = len(df)

    # среднее значение заработной платы по найденным вакансиям
    avg_salary = df['rur_avg_salary'].mean().round(2)

    # список ссылок на вакансии
    url_list = df['url'].to_list()

    return vacancies_count, avg_salary, url_list

# проверка функции
result = vacancy_finder(salary=400000, test_task=False, vacancy_part='Python', skill='Python')

print(result)

(16, np.float64(340668.38), ['https://hh.ru/applicant/vacancy_response?vacancyId=46386511', 'https://hh.ru/applicant/vacancy_response?vacancyId=46604456', 'https://hh.ru/applicant/vacancy_response?vacancyId=46458400', 'https://hh.ru/applicant/vacancy_response?vacancyId=46497746', 'https://hh.ru/applicant/vacancy_response?vacancyId=46718244', 'https://hh.ru/applicant/vacancy_response?vacancyId=46718177', 'https://hh.ru/applicant/vacancy_response?vacancyId=46499976', 'https://hh.ru/applicant/vacancy_response?vacancyId=44433173', 'https://hh.ru/applicant/vacancy_response?vacancyId=46705713', 'https://hh.ru/applicant/vacancy_response?vacancyId=46559189', 'https://hh.ru/applicant/vacancy_response?vacancyId=46417735', 'https://hh.ru/applicant/vacancy_response?vacancyId=46462771', 'https://hh.ru/applicant/vacancy_response?vacancyId=46458369', 'https://hh.ru/applicant/vacancy_response?vacancyId=46458120', 'https://hh.ru/applicant/vacancy_response?vacancyId=46373028', 'https://hh.ru/applicant/vacancy_response?vacancyId=46510274'])